place_mapping = {
 'United Republic of Tanzania': 'Tanzania',
 'East Of Tanzania': 'Tanzania',
 'Central Peru': 'Peru',
 'Northern Peru': 'Peru',
 'Maine': 'United States of America',
 'Texas': 'United States of America',
 'Hudson Bay': 'Canada',
 'Northeast Of Taiwan': 'Taiwan',
 'Central California': 'United States of America',
 'California': 'United States of America',
 'Western turkey': 'Turkey',
 'Southeast of the loyalty islands': 'Loyalty Islands',
 'Northern california': 'United States of America',
 'Oregon': 'United States of America',
 'Off the east coast of the north island of new zealand': 'New Zealand',
 'Off the west coast of northern sumatra': 'Indonesia',
 'Gulf of california': 'United States of America',
 'South georgia and the south sandwich islands': 'Sandwich islands',
 'Off the west coast of the south island of new zealand': 'New Zealand',
 'America': 'United States of America',
 'Ca': 'United States of America',
 'CA': 'United States of America',
 'Eastern sea of japan': 'Japan',
 'Sea of japan': 'Japan',
 'South island of new zealand': 'New zealand',
 'Near the west coast of colombia': 'Colombia',
 'Micronesia': 'Federated States of Micronesia',
 'Central california': 'United States of America',
 'Southeast of taiwan': 'Taiwan',
 'Off the east coast of the south island of new zealand': 'New zealand',
 'Northwest of australia': 'Australia',
 'North of franz josef land': 'Franz Josef island',
 'Near the south coast of myanmar': 'Myanmar',
 'Central turkey': 'Turkey',
 'Off the west coast of the north island of new zealand': 'New zealand',
 'Near the north coast of colombia': 'Colombia',
 'Western australia': 'Australia',
 'North of new zealand': 'New zealand',
 'Near the west coast of yemen': 'Yemen',
 'North of puerto rico': 'Peurto Rico',
 'Eastern turkey': 'Turkey',
 'Off the east coast of the united states': 'United States of America',
 'Southwestern pakistan': 'Pakistan',
 'Off the south coast of australia': 'Australia',
 'West of australia': 'Australia',
 'Northwest of new zealand': 'New Zealand',
 'Near the southeast coast of australia': 'Australia',
 'South australia': 'Australia',
 'Southeastern iran': 'Iran',
 'Near the north coast of greenland': 'Greenland',
 'Southeast of australia': 'Australia',
 'Off the west coast of baja california': 'United States of America',
 'Western saudi arabia': 'Saudi Arabia',
 'East of australia': 'Australia',
 'Southeastern china': 'China',
 'Northwest of madagascar': 'Madagascar',
 'The netherlands': 'Netherlands',
 'Florida': 'United States of America',
 'Eastern china': 'China',
 'New jersey': 'United States of America',
 'Netherlands antilles': 'Netherlands',
 'Jersey': 'United States of America',
 'Western iran': 'Iran',
 'Massachusetts': 'United States of America',
 'Mississippi': 'United States of America',
 'South carolina': 'United States of America',
 'Sint maarten': 'Saint Maarten',
 'North carolina': 'United States of America',
 'New york': 'United States of America',
 'Arizona': 'United States of America',
 'Central alaska': 'Alaska'
}